spring:
  application:
    name: demo-service-3
  data:
    mongodb:
      host: demo-service-mongo
      database: ts
      port: 27017
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
  

# HTTP Server
server:
  port: 18083  # HTTP (Tomcat) port